apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hands-on
  name: hands-on
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hands-on
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hands-on
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
    env:
    - name: DB_HOST
      value: "192.168.0.1"
    - name: DB_NAME
      value: "true"
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
    resources:
      requests:
        cpu: "10m"
        memory: "50Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"